spring:
  application:
    name: running_for_environment
  datasource:
    url: jdbc:mysql://localhost:3308/running_for_environment
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update